services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: TunisiCartDB
      MYSQL_USER: ${DB_USERNAME:-aeisel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-azerty}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-toor}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mail-dev:
    container_name: mail-dev-trz
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  mysql_data:
